### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by FHaoNan** [maybeluo/KDDCup2020-RL-1st-solution#2]
为什么无法运行啊，
![image](https://user-images.githubusercontent.com/46510408/144166879-290d86ab-9183-44e0-9ee4-255800e30605.png)
我加上了model
但是还是有问题的
![image](https://user-images.githubusercontent.com/46510408/144166938-f12342d2-ae31-4e8f-8260-2e43c2a35c06.png)

**Comment by QihangYang** [comment]
我也遇到了这个问题，请问您解决了吗？

**Comment by maybeluo** [comment]
我这边没遇到过，可能是一些版本问题，比如不同版本或系统下，pickle读写的方式变化

**Comment by TronYY** [comment]
> 我也遇到了这个问题，请问您解决了吗？

后来解决了吗
